vscode:
  extensions:
    - xabikos.JavaScriptSnippets@1.7.2:XXmiw8r7K3Guifex/E73aQ==
    - syler.sass-indented@1.6.7:gAbIL/5IWvH0xYAbwe0Vag==
    - naumovs.color-highlight@2.3.0:6nKORbxgnWjNaN6xACiaQQ==
    - dsznajder.es7-react-js-snippets@2.4.3:hx3eTJAy1EbZG5qQ6lxrdA==